#!/bin/bash
set -e

# Gitea database configuration
APP_USER_PASSWORD=$(cat /run/secrets/gitea_db_password)

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $GITEA_DB_USER WITH PASSWORD '${APP_USER_PASSWORD}';
    CREATE DATABASE $GITEA_DB_NAME OWNER $GITEA_DB_USER;
    GRANT ALL PRIVILEGES ON DATABASE $GITEA_DB_NAME TO $GITEA_DB_USER;
EOSQL